### ISSUE TITLE
Current Anorm Version uses java.util.date

### ISSUE THREAD

**Issue by anthonyjoeseph** [gnomff/ScalatraSeed#3]
java.time.LocalDate isn't used until anorm version 2.4, which I believe requires play version 2.6, which I believe requires scala version 2.11.11, rather than 2.11.8

https://stackoverflow.com/questions/30256947/how-can-i-format-datetime-using-anorm
https://www.playframework.com/documentation/2.6.x/Highlights26

Since scalatraseed uses gradle instead of sbt, finding documentation to help update this is tricky.

**Comment by tecklund** [comment]
We are currently on anorm 2.5.3, this should be fine. I'll double check when I get home

**Comment by tecklund** [comment]
The issue was not with anorm, it was with the Jackson serializer. I added the latest json4s ext package in and added the java.time serializers so it's good to go
